version: '3.8'
services:
  server-monitor:
    build: .
    ports:
      - "8181:5000"
    volumes:
      - /var/log:/host/var/log:ro
      - /proc:/host/proc:ro
      - /tmp:/tmp  # Aggiunto per consentire la persistenza dei file di monitoraggio

    environment:
      - BOT_TOKEN=xxxxxxxxxxxxxxx
      - CHAT_ID=1xxxxxxxxxxxxx
    restart: always
    cap_add:
      - NET_ADMIN  # Aggiunto per consentire l'accesso a informazioni di rete
    network_mode: "host"  # Permette al container di accedere direttamente alla rete dell'host
